#!/bin/bash
set -eo pipefail

# You can now add delay line to pubkey.txt file
source pubkey.txt
overide_args="$@"
seed_ip=`getent hosts zero.rtbseeds.com | awk '{ print $1 }'`
rtb_binary='./qt/rtb-qt'

if [ -z "$delay" ]; then delay=20; fi

./listassetchainparams | while read args; do
  gen=""
  if [ $[RANDOM % 10] == 1 ]; then
      gen=" -gen -genproclimit=1"
  fi

  $rtb_binary $gen $args $overide_args -pubkey=$pubkey -addnode=$seed_ip &
  sleep $delay
done
